apiVersion: batch/v1
kind: Job
metadata:
  name: client-registration
spec:
  template:
    spec:
      containers:
      - name: client
        image: client_registration:latest
        imagePullPolicy: Never
        env:
        - name: KEYCLOAK_URL
          value: "http://keycloak:8080"
        - name: KEYCLOAK_REALM
          value: "master"
        - name: KEYCLOAK_ADMIN_USERNAME
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
        - name: CLIENT_NAME
          value: "client_registration_k8s"
      restartPolicy: Never
  backoffLimit: 1
